# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'jumbosmash' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Crash'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Firebase/Auth'

end
